// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_simple_arithmetic 22
#define SYS_make_duplicate 23
#define SYS_show_process_family 24
#define SYS_grep_syscall 25
#define SYS_set_priority 26
#define SYS_start_measuring  27
#define SYS_stop_measuring   28
#define SYS_print_info       29
#define SYS_testlock_acquire  30
#define SYS_testlock_release  31
#define SYS_rwlock_acquire_read   32
#define SYS_rwlock_release_read   33
#define SYS_rwlock_acquire_write  34
#define SYS_rwlock_release_write  35
#define SYS_getlockstat 36
#define SYS_plock_acquire 37 
#define SYS_plock_release 38 
#define SYS_newpt_write  39
#define SYS_newpt_read   40
#define SYS_newpt_report  41
#define SYS_newpt_setpolicy 42   
